[package]
name = "weather-lion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "*", features = ["json", "charset"] }
serde = { version = "1", features = ["derive"] }
indicatif = { version = "0.17.0-rc.10"}

